version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Admin1234
      MYSQL_DATABASE: EwashingDB
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - backend

  spring-api:
    build: .
    container_name: spring-api
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/EwashingDB?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Admin1234
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
